### ISSUE TITLE
thanks for the code 

### ISSUE THREAD

**Issue by kuw13** [seega/MultichainPrivateKeysChecker#1]
\Python\Python311\Lib\site-packages\bloomfilter\bloomfilter.py", line 40, in load
    assert bloom_filter.__filter.length() == filter_size or bloom_filter.__filter.length() == filter_size + (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bitarray.bitarray' object has no attribute 'length'

i git that error

**Comment by seega** [comment]
> \Python\Python311\Lib\site-packages\bloomfilter\bloomfilter.py", line 40, in load assert bloom_filter.__filter.length() == filter_size or bloom_filter.__filter.length() == filter_size + ( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'bitarray.bitarray' object has no attribute 'length'
> 
> i git that error

pip install bit bitarray==1.9.2

**Comment by kuw13** [comment]
i did install it

**Comment by seega** [comment]
> i did install it

Windows: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by kuw13** [comment]
I UPDATED VISAL 

THANKS
